title: Cyrus Baruc
# logo: assets/img/headshot_001.png
# description:
show_downloads: true
theme: jekyll-theme-dinky
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
